--- 
reminder: 
  countEndpoint: "http://learner-service/reminder/v1/length"
  fallBackMeaning: "very hungry"
  fallbackExpression: "ravenous"
  minInteger: 1
  phraseEndpoint: "http://learner-service/reminder/v1/expression?id="
  saveEndpont: "http://admin-service/AdminReminder/v1/save"
server: 
  port: 8087